
package bft_dti;

public enum BFTMapRequestType {
    // PUT, GET, SIZE, REMOVE, KEYSET, VALUES, ENTRYSET
    PUT_COIN, COIN_KEYSET, COIN_USERMAP, SPEND_COINS, NFT_USERMAP, NFT_KEYMAP, PUT_NFT,
    PUT_NFT_REQUEST, REMOVE_NFT_REQUEST, NFT_REQUESTS, TRANSFER_NFT
    // COIN_PUT, COIN_ENTRYSET
}
